apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sentry-ingress
  namespace: f-paas
  labels:
    layer: f-paas
    env: all
    app: sentry-sentry
    name: sentry-sentry-server
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sentry-svc
                port:
                  number: 8888